# Generated by Django 4.2.7 on 2023-12-13 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("forum", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "Other"),
                            (1, "Illegal Content"),
                            (2, "Spam"),
                            (3, "Harassment"),
                            (4, "Hate Speech"),
                            (5, "Violence"),
                            (6, "Delete My Post"),
                        ],
                        default=0,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                (
                    "progress",
                    models.IntegerField(
                        choices=[(0, "Open"), (1, "In Progress"), (2, "Closed")],
                        default=0,
                    ),
                ),
                ("reply", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="forum.post",
                    ),
                ),
            ],
        ),
    ]
