# Generated by Django 4.2.7 on 2023-11-27 02:10

import bluebasin.apps.identity.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Identity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default=bluebasin.apps.identity.models.Identity.generate_random_name,
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                ("show_as_admin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deprecated_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
