# Generated by Django 4.2.7 on 2023-11-27 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="identity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="identities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
